/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/datasets/valeo/Veh01_20230208_105703_076_CAM_NFV_FW_CE_NO_ENC.npzenv  && cd ./../../../  && python demo.py --imagedir=./datasets/valeo/'{}'  --op0it [00:00, ?it/s]droidcalib.pth

/home/it4i-atay/.conda/envs/droidenv/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1640811803361/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
300it [03:40,  1.36it/s]
################################
Global BA Iteration #1
Global BA Iteration #2
Global BA Iteration #3
Global BA Iteration #4
Global BA Iteration #5
Global BA Iteration #6
Global BA Iteration #7
################################
Global BA Iteration #1
Global BA Iteration #2
Global BA Iteration #3
Global BA Iteration #4
Global BA Iteration #5
Global BA Iteration #6
Global BA Iteration #7
Global BA Iteration #8
Global BA Iteration #9
Global BA Iteration #10
Global BA Iteration #11
Global BA Iteration #12
################################
Initial intrinsics:
fx = 2386.0, fy = 2386.0, ppx = 1448.0, ppy = 938.0
Estimated intrinsics:
fx = 5163.90, fy = 4507.28, ppx = 1545.79, ppy = 1233.56, xi = -0.115
/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/datasets/valeo/Veh01_20230208_105703_076_CAM_SUR_FR_CE_NO_ENC.npz
0it [00:00, ?it/s]droidcalib.pth
/home/it4i-atay/.conda/envs/droidenv/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1640811803361/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
7it [00:03,  2.01it/s]
Traceback (most recent call last):
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/demo.py", line 187, in <module>
    droid.track(t, image, intrinsics=intrinsics)
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/droid.py", line 77, in track
    self.frontend()
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/droid_frontend.py", line 113, in __call__
    self.__initialize()
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/droid_frontend.py", line 84, in __initialize
    self.graph.update(1, use_inactive=True)
  File "/home/it4i-atay/.conda/envs/droidenv/lib/python3.9/site-packages/torch/autocast_mode.py", line 198, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/factor_graph.py", line 203, in update
    coords1, mask = self.video.reproject(self.ii, self.jj)
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/depth_video.py", line 169, in reproject
    pops.general_projective_transform(Gs, self.disps[None], self.intrinsics[None],
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/geom/projective_ops.py", line 155, in general_projective_transform
    return projective_transform_mei(poses, depths, intr, ii, jj, jacobian, return_depth)
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/geom/projective_ops.py", line 164, in projective_transform_mei
    raise Exception('nan values in depth')
Exception: nan values in depth
/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/datasets/valeo/Veh01_20230208_105703_076_CAM_SUR_RE_CE_SO_ENC.npz
0it [00:00, ?it/s]droidcalib.pth
/home/it4i-atay/.conda/envs/droidenv/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1640811803361/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
7it [00:03,  2.17it/s]
Traceback (most recent call last):
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/demo.py", line 187, in <module>
    droid.track(t, image, intrinsics=intrinsics)
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/droid.py", line 77, in track
    self.frontend()
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/droid_frontend.py", line 113, in __call__
    self.__initialize()
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/droid_frontend.py", line 84, in __initialize
    self.graph.update(1, use_inactive=True)
  File "/home/it4i-atay/.conda/envs/droidenv/lib/python3.9/site-packages/torch/autocast_mode.py", line 198, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/factor_graph.py", line 203, in update
    coords1, mask = self.video.reproject(self.ii, self.jj)
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/depth_video.py", line 169, in reproject
    pops.general_projective_transform(Gs, self.disps[None], self.intrinsics[None],
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/geom/projective_ops.py", line 155, in general_projective_transform
    return projective_transform_mei(poses, depths, intr, ii, jj, jacobian, return_depth)
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/geom/projective_ops.py", line 164, in projective_transform_mei
    raise Exception('nan values in depth')
Exception: nan values in depth
/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/datasets/valeo/Veh01_20230208_105703_076_CAM_SUR_WM_LE_WE_ENC.npz
0it [00:00, ?it/s]droidcalib.pth
/home/it4i-atay/.conda/envs/droidenv/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1640811803361/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
8it [00:03,  2.28it/s]
Traceback (most recent call last):
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/demo.py", line 187, in <module>
    droid.track(t, image, intrinsics=intrinsics)
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/droid.py", line 77, in track
    self.frontend()
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/droid_frontend.py", line 113, in __call__
    self.__initialize()
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/droid_frontend.py", line 84, in __initialize
    self.graph.update(1, use_inactive=True)
  File "/home/it4i-atay/.conda/envs/droidenv/lib/python3.9/site-packages/torch/autocast_mode.py", line 198, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/factor_graph.py", line 203, in update
    coords1, mask = self.video.reproject(self.ii, self.jj)
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/depth_video.py", line 169, in reproject
    pops.general_projective_transform(Gs, self.disps[None], self.intrinsics[None],
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/geom/projective_ops.py", line 155, in general_projective_transform
    return projective_transform_mei(poses, depths, intr, ii, jj, jacobian, return_depth)
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/geom/projective_ops.py", line 164, in projective_transform_mei
    raise Exception('nan values in depth')
Exception: nan values in depth
/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/datasets/valeo/Veh01_20230208_105703_076_CAM_SUR_WM_RI_EA_ENC.npz
0it [00:00, ?it/s]droidcalib.pth
/home/it4i-atay/.conda/envs/droidenv/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1640811803361/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
7it [00:03,  2.17it/s]
Traceback (most recent call last):
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/demo.py", line 187, in <module>
    droid.track(t, image, intrinsics=intrinsics)
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/droid.py", line 77, in track
    self.frontend()
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/droid_frontend.py", line 113, in __call__
    self.__initialize()
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/droid_frontend.py", line 84, in __initialize
    self.graph.update(1, use_inactive=True)
  File "/home/it4i-atay/.conda/envs/droidenv/lib/python3.9/site-packages/torch/autocast_mode.py", line 198, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/factor_graph.py", line 203, in update
    coords1, mask = self.video.reproject(self.ii, self.jj)
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/depth_video.py", line 169, in reproject
    pops.general_projective_transform(Gs, self.disps[None], self.intrinsics[None],
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/geom/projective_ops.py", line 155, in general_projective_transform
    return projective_transform_mei(poses, depths, intr, ii, jj, jacobian, return_depth)
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/geom/projective_ops.py", line 164, in projective_transform_mei
    raise Exception('nan values in depth')
Exception: nan values in depth
/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/datasets/valeo/Veh01_20230208_105703_076_CAM_WFV_FW_CE_NO_ENC.npz
0it [00:00, ?it/s]droidcalib.pth
/home/it4i-atay/.conda/envs/droidenv/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1640811803361/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
300it [01:24,  3.53it/s]
################################
Global BA Iteration #1
Global BA Iteration #2
Global BA Iteration #3
Global BA Iteration #4
Global BA Iteration #5
Global BA Iteration #6
Global BA Iteration #7
################################
Global BA Iteration #1
Global BA Iteration #2
Global BA Iteration #3
Global BA Iteration #4
Global BA Iteration #5
Global BA Iteration #6
Global BA Iteration #7
Global BA Iteration #8
Global BA Iteration #9
Global BA Iteration #10
Global BA Iteration #11
Global BA Iteration #12
################################
Initial intrinsics:
fx = 2386.0, fy = 2386.0, ppx = 1448.0, ppy = 938.0
Estimated intrinsics:
fx = 3447.26, fy = 2463.40, ppx = 1509.15, ppy = 928.89, xi = 1.657
/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/datasets/valeo/Veh01_20230208_105703_076_CAM_WFV_RW_CE_SO_ENC.npz
0it [00:00, ?it/s]droidcalib.pth
/home/it4i-atay/.conda/envs/droidenv/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1640811803361/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
105it [00:57,  1.84it/s]
Traceback (most recent call last):
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/demo.py", line 187, in <module>
    droid.track(t, image, intrinsics=intrinsics)
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/droid.py", line 77, in track
    self.frontend()
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/droid_frontend.py", line 117, in __call__
    self.__update()
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/droid_frontend.py", line 51, in __update
    self.graph.update(None, None, use_inactive=True)
  File "/home/it4i-atay/.conda/envs/droidenv/lib/python3.9/site-packages/torch/autocast_mode.py", line 198, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/factor_graph.py", line 203, in update
    coords1, mask = self.video.reproject(self.ii, self.jj)
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/depth_video.py", line 169, in reproject
    pops.general_projective_transform(Gs, self.disps[None], self.intrinsics[None],
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/geom/projective_ops.py", line 155, in general_projective_transform
    return projective_transform_mei(poses, depths, intr, ii, jj, jacobian, return_depth)
  File "/home/it4i-atay/calibration/intrinsicCalibrationMatrix/DroidCalib/droid_slam/geom/projective_ops.py", line 164, in projective_transform_mei
    raise Exception('nan values in depth')
Exception: nan values in depth
